const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game,emptyBoard,findMatches,collapse,MAX_HP}=require('../src/core.js');
function tick(g,n=60){for(let i=0;i<n;i++)g.tick(1/60);}
test('horizontal, vertical, intersections; no diagonal or 2-match',()=>{
 const b=emptyBoard(); b[7]=[0,0,0,1,1,2]; b[5][1]=b[6][1]=0;
 assert.equal(findMatches(b).length,5);
 const c=emptyBoard();c[7][0]=c[6][1]=c[5][2]=1;c[7][4]=c[7][5]=2;assert.equal(findMatches(c).length,0);
});
test('gravity packs columns in original order',()=>{const b=emptyBoard();b[1][0]=3;b[4][0]=0;b[6][0]=2;collapse(b);assert.deepEqual(b.map(r=>r[0]),[-1,-1,-1,-1,-1,3,0,2]);});
test('rotation and collision stay inside board through 2000 operations',()=>{const g=new Game(42);let checked=0;for(let i=0;i<2000;i++){if(g.phase!=='playing')break;const action=i%5;if(action===0)g.rotate();if(action===1)g.move(-1);if(action===2)g.move(1);if(action===3)g.down();if(action===4)tick(g,25);if(g.active){assert.ok(g.fits(g.active));assert.ok(g.cells().every(c=>c.x>=0&&c.x<6&&c.y>=-1&&c.y<8));checked++;}}assert.ok(checked>50);});
test('first match deploys calico, earns score/SP, and preserves pieces',()=>{const g=new Game(1);g.moveTo(0);g.drop();tick(g,24);assert.ok(g.units.some(u=>u.type===0));assert.ok(g.score>=300);assert.ok(g.sp>=15);assert.equal(g.matched,3);assert.equal(g.board.flat().filter(v=>v>=0).length,7);});
test('vertical match falls into a horizontal 2-chain',()=>{const g=new Game(2);g.active=null;g.board=emptyBoard();for(let y=5;y<8;y++)g.board[y][1]=0;g.board[4][1]=1;g.board[7][0]=g.board[7][2]=1;g.checkMatches();tick(g,46);assert.equal(g.maxChain,2);assert.equal(g.matched,6);assert.ok(g.units.some(u=>u.type===0));assert.ok(g.units.some(u=>u.type===1));});
test('four cat roles and reinforcement limits',()=>{const g=new Game(3);g.hp=100;g.summon(1);assert.equal(g.hp,118);g.summon(2);assert.equal(g.shield,25);g.summon(0);g.summon(3);for(let i=0;i<40;i++)g.summon(0);assert.equal(g.units.length,4);assert.equal(g.units.find(u=>u.type===0).power,3);});
test('shield absorbs before castle HP; losing is terminal',()=>{const g=new Game(4);g.shield=20;g.hurtCastle(15);assert.equal(g.hp,MAX_HP);assert.equal(g.shield,5);g.hurtCastle(10);assert.equal(g.hp,195);g.hurtCastle(300);assert.equal(g.phase,'lost');const t=g.time;tick(g,100);assert.equal(g.time,t);});
test('skill requires full SP, clears only bottom 2 rows and spends once',()=>{const g=new Game(5);assert.equal(g.skill(),false);g.sp=100;g.hp=100;const active=JSON.stringify(g.active);assert.equal(g.skill(),true);assert.equal(g.sp,0);assert.equal(g.hp,148);assert.equal(g.skillCount,1);assert.equal(g.board.flat().filter(v=>v>=0).length,0);assert.equal(JSON.stringify(g.active),active);assert.equal(g.skill(),false);});
test('area attack hits nearby enemies; basic attack only one',()=>{for(const type of [0,3]){const g=new Game(7);g.summon(type);g.units[0].x=120;g.units[0].cooldown=0;g.spawnEnemy();g.spawnEnemy();g.enemies.forEach((e,i)=>{e.x=95+i*5;e.hp=e.maxHp=90;});g.combat(.01);assert.equal(g.enemies.filter(e=>e.hp<90).length,type===3?2:1);}});
test('ghost revives once and then counts as defeated',()=>{const g=new Game(8);g.spawnEnemy();const e=g.enemies[0];e.type=3;e.hp=0;g.collectDefeated();assert.equal(g.enemies.length,1);assert.ok(e.revived);e.hp=0;g.collectDefeated();assert.equal(g.enemies.length,0);assert.equal(g.kills,1);});
test('top-out has clear loss and cannot write out of bounds',()=>{const g=new Game(10);g.board=Array.from({length:8},()=>[0,1,2,3,0,1]);g.spawnPiece();assert.equal(g.phase,'lost');assert.equal(g.active,null);assert.equal(g.board.length,8);assert.equal(g.drop(),false);});
test('campaign advances all waves and wins after last clear',()=>{const g=new Game(11);for(let wave=1;wave<=5;wave++){assert.equal(g.wave,wave);g.spawned=g.waveTotal;g.enemies=[];g.board=emptyBoard();g.spawnPiece();tick(g,182);}assert.equal(g.phase,'won');assert.equal(g.wave,5);});
test('save round-trip is deterministic, including match resolution',()=>{const g=new Game(12);g.moveTo(0);g.drop();const h=Game.restore(g.serialize());assert.ok(h);tick(g,100);tick(h,100);assert.deepEqual(h.serialize(),g.serialize());});
test('corrupt and adversarial saves are rejected without crashing',()=>{const g=new Game(13);for(const mutate of [s=>s.hp=NaN,s=>s.wave=6,s=>s.active.rot=7,s=>s.board[2][0]=9,s=>s.next=[9,0],s=>s.enemies=[{}],s=>s.matches=[0],s=>s.bag={},s=>s.phase='won',s=>s.waveTotal=99,s=>s.units=[{}]]){const s=g.serialize();mutate(s);assert.equal(Game.restore(s),null);}assert.equal(Game.restore(null),null);assert.equal(Game.restore({}),null);});
test('time step is bounded and long suspended frames do not advance',()=>{const g=new Game(14);g.tick(10);g.tick(NaN);g.tick(-1);assert.equal(g.time,0);g.tick(1/60);assert.ok(g.time>0);});
test('long reinforced deployments retain a valid resumable save',()=>{const g=new Game(15);g.summon(2);for(let i=0;i<9000;i++){if(i%600===0)g.summon(2);g.combat(1/60);}assert.equal(g.units[0].cooldown,0);assert.ok(Game.restore(g.serialize()));});
